### ISSUE TITLE
Dbimport issue with CWMS/Oracle database

### ISSUE THREAD

**Issue by ktarbet** [opendcs/opendcs#1008]
**Describe the bug**
The Dbimport program is only doing a partial import of XML on CWMS/Oracle database.

**To Reproduce**
1. dbimport -d 3 -r -P ${DCSTOOL_USERDIR}/NWK.profile ./dbexport-nwk.xml
2. Errors occur, and only some data is imported  (see below)

** Next Steps in Debugging  ***
Check the following parts in the CWMS Database
| Name | Purpose | What to Check |
|---|---|---|
|CWMS_20.AT_CWMS_TS_ID_U01| unique constraint for time series ID | look at Office ID |
|CCP.SITE_DESIGNATOR_EXPIRATION_UNIQUE| unique constraint for site designation expiration| is the siteid of the profile included?|
|CWMS_20.AT_BASE_LOCATION_T01|trigger for base location| check trigger for officeid|

**Expected behavior**
All Sites and platforms should be imported

**Desktop/ServerSide:**
 - OS: Importing from Windows into Solaris/Oracle

**Additional context**
Specific Errors below:

```log

WARNING java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (CCP.SITE_DESIGNATOR_EXPIRATION_UNIQUE) violated

https://docs.oracle.com/error-help/db/ora-00001/
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:709)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:609)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1290)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1100)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:408)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:483)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:170)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1148)
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1702)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1444)
	at oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:2244)
	at oracle.jdbc.driver.OracleStatement.executeLargeUpdate(OracleStatement.java:2203)
	at oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:2188)
	at oracle.jdbc.driver.OracleStatementWrapper.executeUpdate(OracleStatementWrapper.java:320)
	at oracle.ucp.jdbc.proxy.oracle$1ucp$1jdbc$1proxy$1oracle$1StatementProxy$2oracle$1jdbc$1internal$1OracleStatement$$$Proxy.executeUpdate(Unknown Source)
	at decodes.sql.SqlDbObjIo.executeUpdate(SqlDbObjIo.java:304)
	at decodes.sql.PlatformListIO.insert(PlatformListIO.java:790)
	at decodes.sql.PlatformListIO.writePlatform(PlatformListIO.java:650)
	at decodes.cwms.CwmsPlatformListIO.writePlatform(CwmsPlatformListIO.java:49)
	at decodes.sql.SqlDatabaseIO.writePlatform(SqlDatabaseIO.java:1342)
	at decodes.db.Platform.write(Platform.java:549)
	at decodes.dbimport.DbImport.writeTheChanges(DbImport.java:1579)
	at decodes.dbimport.DbImport.importDatabase(DbImport.java:222)
	at decodes.dbimport.DbImport.main(DbImport.java:181)
Caused by: Error : 1, Position : 0, SQL = INSERT INTO Platform (id, agency, isProduction, siteId, configId, description, lastModifyTime, expiration, platformDesignator) VALUES (7219020, 'USBR', 'FALSE', 19776030, 1928020, 'USBR HVR Helena Valley Irrigation & Municipal Supply', to_date('26-Mar-2025 16:50:47', 'DD-MON-YYYY HH24:MI:SS'), NULL, 'web'), Original SQL = INSERT INTO Platform (id, agency, isProduction, siteId, configId, description, lastModifyTime, expiration, platformDesignator) VALUES (7219020, 'USBR', 'FALSE', 19776030, 1928020, 'USBR HVR Helena Valley Irrigation & Municipal Supply', to_date('26-Mar-2025 16:50:47', 'DD-MON-YYYY HH24:MI:SS'), NULL, 'web'), Error Message = ORA-00001: unique constraint (CCP.SITE_DESIGNATOR_EXPIRATION_UNIQUE) violated
```

```log
https://docs.oracle.com/error-help/db/ora-00001/
FAILURE CwmsSiteDAO cwmsDbLoc.store failed for officeId=NWDM, cwmsName=HAST-Tailwater, state=MO, tz=US/Central, locType=null, lat=38.2630028, lon=-93.4054861, elev=null, vertDatum=NGVD29, horzDatum=null, pubName=null, longName=, desc=null, nearestCity=Warsaw
FAILURE CwmsSiteDAO STACK TRACE FOLLOWS:
FAILURE CwmsSiteDAO Error in CwmsLocJdbc.store for site 'STON': java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (CWMS_20.AT_CWMS_TS_ID_U01) violated
ORA-06512: at "CWMS_20.CWMS_LOC", line 3708
ORA-06512: at "CWMS_20.CWMS_LOC", line 3664
ORA-06512: at "CWMS_20.CWMS_LOC", line 1453
ORA-06512: at "CWMS_20.AT_BASE_LOCATION_T01", line 12
ORA-06512: at "CWMS_20.CWMS_TS_ID", line 285
ORA-06512: at "CWMS_20.CWMS_TS_ID", line 513
ORA-06512: at "CWMS_20.CWMS_TS_ID", line 513
ORA-06512: at "CWMS_20.AT_BASE_LOCATION_T01", line 3
ORA-04088: error during execution of trigger 'CWMS_20.AT_BASE_LOCATION_T01'
ORA-06512: at "CWMS_20.CWMS_LOC", line 1443
ORA-06512: at "CWMS_20.CWMS_LOC", line 3636
ORA-06512: at line 1


```

**Comment by MikeNeilson** [comment]
Have you tried adding this data to the integration tests? I'm curious as to if it's an issue with a fresh database.

**Comment by MikeNeilson** [comment]
You probably don't even need to go so far as creating a new file, though you code.

There's already several sites that are important and you could just add to that file. When the tests run there's an import log so you can look and see if it's an issue before deciding on more detailed work.

**Comment by MikeNeilson** [comment]
Check the HEC T7 CCP schema. I may not have migrated that fix to the code yet.

As for the siteid, no. At least not directly in CWMS. The platform should still have it's own office code and that should be in that constraint as well.

**Comment by ktarbet** [comment]
Looks like we need to add OfficeID to the platform table?  
And to the V7.0__initial_flyway_marker.sql?

Below is from the HEC T7 CCP schema.

```sql
  CREATE TABLE "CCP"."PLATFORM" 
   (	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"AGENCY" VARCHAR2(64 BYTE), 
	"ISPRODUCTION" VARCHAR2(5 BYTE) DEFAULT 'false' NOT NULL ENABLE, 
	"SITEID" NUMBER(18,0), 
	"CONFIGID" NUMBER(18,0), 
	"DESCRIPTION" VARCHAR2(400 BYTE), 
	"LASTMODIFYTIME" DATE NOT NULL ENABLE, 
	"EXPIRATION" DATE, 
	"PLATFORMDESIGNATOR" VARCHAR2(24 BYTE), 
	 PRIMARY KEY ("ID")
.....
	 CONSTRAINT "SITE_DESIGNATOR_EXPIRATION_UNIQUE" UNIQUE ("SITEID", "PLATFORMDESIGNATOR", "EXPIRATION")
....
  TABLESPACE "CCP_DATA" ;

```

**Comment by MikeNeilson** [comment]
yes, but two things

1. for the tables we use office_id (the numeric value)
2. Even for this small change it would be V7.1_platform-update.sql or some such name.

The existing V7.0__initial_flyway_marker.sql is out in the wild so it must be assumed it is applied. If you alter an existing versioned migration the schema update would fail on that system as the checksum will have changed.

**Comment by ktarbet** [comment]
Here is a draft   V7.1_platform-office-id.sql

```sql
ALTER TABLE PLATFORM DROP CONSTRAINT site_designator_unique;

ALTER TABLE PLATFORM
 ADD (
     db_office_code INTEGER DEFAULT ${DEFAULT_OFFICE_CODE},
     CONSTRAINT office_site_designator_unique UNIQUE (db_office_code, SITEID, PLATFORMDESIGNATOR, EXPIRATION)
 );


```

**Comment by MikeNeilson** [comment]
I would add the new constraint first. But otherwise that looks correct and reasonable.

**Comment by ktarbet** [comment]
Results from today's testing on main branch, with an empty CWMS database.

Goal -- reproduce issue where multiple offices/profiles can't import the same platform.

Steps to reproduce:
* import the attached dbexport-drsd.xml file with dbimport for two different offices.
* Which ever office-profile is using for importing, first shows up in  ccp.platformconfig table (and in the dbedit UI)
* The second import (different office) does not show up in platformconfig.

note: I was focused on platformconfig, which has a db_office_code column.

<img width="587" alt="Image" src="https://github.com/user-attachments/assets/7d0f9eff-d254-47d5-9ad2-e75a00d44fa4" />

[dbexport-drsd.zip](https://github.com/user-attachments/files/20196443/dbexport-drsd.zip)


### Next Steps

Add db_office_code to ccp.platform, and any other ccp.table.    This will be done in a flyway SQL file, that will be executed by the manageDatabase application.   


### Background

CWMS database handles multiple offices using the Virtual Private Database (VPD) feature that handles the filtering by office_code at the database layer; so the Java code doesn't need to handle all the details.

**Comment by ktarbet** [comment]
I have a set of steps in the link below to setup an 'clean' OpenDCS CWMS-Oracle database 

https://github.com/ktarbet/learning/blob/master/opendcs.md

**Comment by MikeNeilson** [comment]
It's definitely part of the issue. Most likely for that particular site the lan/long isn't valid for the given nearest city and county if defined.

It would be useful if more details could be printed out, like a callback that each SiteDAO implementations to log any actual Site saving errors.

**Comment by MikeNeilson** [comment]
That might be an issue with how things get imported from the XML file.

Within the CWMS Oracle database you might get that if the parent Enum was hidden by the VPD mechanism. The values aren't, so you have an EnumValue with an Enum foreign reference that *exists*, but the current user can't see as it's hidden by the VPD mechanism... hence it appears Orphaned, even though it technically isn't.

**Comment by ktarbet** [comment]
There is a comment in the code, where the Orphaned message occurs

```java
/**				 
				 * This could also be a single query with a join.
				 * though a little trickier with the different versions columns
				 */

```

Using a Join may fix the Orphaned message, and avoid the need for db_office_code in the enumvalue table.

**Comment by MikeNeilson** [comment]
On that particular one yes, there's no additional unique constraints the would require being updated. On say Platforms, that needs the db_office_code to properly allow the constraint.

**Comment by MikeNeilson** [comment]
Though, to be fair to ourselves. do we want duplicate platforms per office? I think the answer is yes beyond our current attempt to intentionally duplicate things, they might just share a name (we're really good and reusing names for these stations.)

**Comment by ktarbet** [comment]
Does the CWMS-Oracle Schema need to keep supporting DECODES_DB_6 in the EnumSqlDao?    I also see DECODES_DB_10 ;  I thought version 7 was the latest.

**Comment by ktarbet** [comment]
Status Update for multi office. 



### after initial setup of CCP schema ( as HQ)

| table            | count | office |
|------------------|-------|--------|
| engineeringunit  | 160   | HQ     |
| enum             | 21    | HQ     |
| enumvalue        | 134   | HQ     |
| datatype         | 308   | HQ     |
| datapresentation | 320   | HQ     |
| datasource       | 5     | HQ     |


### After importing xml as user: NWDM

```bat
dbimport  -P nwdm-test.profile nwdm-all.xml
```

note: HQ filtered out  exception interesting datapresentation result.

| table                  | count  | office |
|------------------------|-------:|--------|
| platform               |   1588 | NWDM   |
| platformconfig         |    775 | NWDM   |
| configsensor           |   3324 | NWDM   |
| configsensordatatype   |   4916 | NWDM   |
| configsensorproperty   |  12973 | NWDM   |
| decodesscript          |   1059 | NWDM   |
| engineeringunit        |    159 | NWDM   |
| enum                   |     23 | NWDM   |
| enumvalue              |    138 | NWDM   |
| equipmentmodel         |      6 | NWDM   |
| equipmenproperty       |      8 | NWDM   |
| datatype               |    222 | NWDM   |
| datapresentation       |    320 | HQ     |
| datasource             |     40 | NWDM   |




### After importing xml as user: NWK

note: HQ filtered out  exception interesting datapresentation result.

```bat
dbimport  -P nwk-test.profile nwdm-all.xml
```

| table                     | count  | office |
|---------------------------|-------:|--------|
| platform:                 |   1588 | NWDM   |
| platform:                 |   1588 | NWK    |
| platformconfig:           |    775 | NWDM   |
| platformconfig:           |    775 | NWK    |
| configsensor:             |   3324 | NWDM   |
| configsensor:             |   3324 | NWK    |
| configsensordatatype:     |   4916 | NWDM   |
| configsensordatatype:     |   4916 | NWK    |
| configsensorproperty:     |  12973 | NWDM   |
| configsensorproperty:     |  12973 | NWK    |
| decodesscript:            |   1059 | NWDM   |
| decodesscript:            |   1059 | NWK    |
| engineeringunit:          |    159 | NWK    |
| engineeringunit:          |    159 | NWDM   |
| enum:                     |     23 | NWDM   |
| enum:                     |     23 | NWK    |
| enumvalue:                |    138 | NWK    |
| enumvalue:                |    138 | NWDM   |
| equipmentmodel:           |      6 | NWDM   |
| equipmentmodel:           |      6 | NWK    |
| equipmenproperty:         |      8 | NWDM   |
| equipmenproperty:         |      8 | NWK    |
| datatype:                 |    222 | NWDM   |
| datatype:                 |    222 | NWK    |
| datapresentation:         |    320 | HQ     |
| datasource:               |     40 | NWDM   |
| datasource:               |     40 | NWK    |

**Comment by MikeNeilson** [comment]
That shouldn't be possible. the vpd system is complete once the database side of the migration is done.

and the connection retrieval sets the session context before any operations are performed.

**Comment by ktarbet** [comment]
Thanks.  I didn't understand the VPD is ready after mm.migrate();   

I'm getting the error below.    And looking at the VPD policy, (afterMigrate__vpd_policy.sql)  I don't see where insert is handled.

https://github.com/opendcs/opendcs/blob/main/java/opendcs/src/main/resources/db/CWMS-Oracle/callbacks/afterMigrate__vpd_policy.sql


```sql
DBG2    06/18/25 15:06:20 Executing update query 'INSERT INTO DataPresentation VALUES (3001, 3001, 14001, 'in', NULL, 2, NULL, NULL)'
DBG1    06/18/25 15:06:20 decodes.sql.PresentationGroupListIO.setConnection(null)
FAILURE 06/18/25 15:06:20 Could not import other modified objs
FAILURE 06/18/25 15:06:20 decodes.db.DatabaseException: writePresentationGroup.
	at decodes.sql.SqlDatabaseIO.writePresentationGroup(SqlDatabaseIO.java:1564)
	at decodes.db.PresentationGroup.write(PresentationGroup.java:408)
	at decodes.dbimport.DbImport.writeTheChanges(DbImport.java:1687)
	at decodes.dbimport.DbImport.importDatabase(DbImport.java:224)
	at decodes.cwms.database.CwmsOracleProvider.loadBaselineData(CwmsOracleProvider.java:162)
	at org.opendcs.database.ManageDatabaseApp.main(ManageDatabaseApp.java:87)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00947: not enough values

https://docs.oracle.com/error-help/db/ora-00947/
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:709)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:609)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1290)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1100)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:408)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:483)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:170)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1148)
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1702)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1444)
	at oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:2244)
	at oracle.jdbc.driver.OracleStatement.executeLargeUpdate(OracleStatement.java:2203)
	at oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:2188)
	at oracle.jdbc.driver.OracleStatementWrapper.executeUpdate(OracleStatementWrapper.java:320)
	at oracle.ucp.jdbc.proxy.oracle$1ucp$1jdbc$1proxy$1oracle$1StatementProxy$2oracle$1jdbc$1internal$1OracleStatement$$$Proxy.executeUpdate(Unknown Source)
	at decodes.sql.SqlDbObjIo.executeUpdate(SqlDbObjIo.java:304)
	at decodes.sql.PresentationGroupListIO.insert(PresentationGroupListIO.java:653)
	at decodes.sql.PresentationGroupListIO.insertAllDataPresentations(PresentationGroupListIO.java:596)
	at decodes.sql.PresentationGroupListIO.insert(PresentationGroupListIO.java:583)
	at decodes.sql.PresentationGroupListIO.write(PresentationGroupListIO.java:475)
	at decodes.sql.SqlDatabaseIO.writePresentationGroup(SqlDatabaseIO.java:1560)
	... 5 more
Caused by: Error : 947, Position : 12, SQL = INSERT INTO DataPresentation VALUES (3001, 3001, 14001, 'in', NULL, 2, NULL, NULL), Original SQL = INSERT INTO DataPresentation VALUES (3001, 3001, 14001, 'in', NULL, 2, NULL, NULL), Error Message = ORA-00947: not enough values

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:717)
	... 25 more

```

**Comment by MikeNeilson** [comment]
That's not a VPD issue. the insert statement is missing a required value. Which is odd, but you have 8 values and there's only 8 columns in the table.

IF you added the office code, then https://github.com/opendcs/opendcs/blob/main/java/opendcs/src/main/resources/db/CWMS-Oracle/callbacks/afterMigrate__activateOfficeTrigger.sql should take care of make sure there's always a value available for that column.

**Comment by ktarbet** [comment]
Yes, I've added the db_office_code column.   The  activateOfficeTriggers.sql code appears to have run since the db_office_code column changed to 'default null' 

I've pushed my work in progress https://github.com/opendcs/opendcs/pull/1170/files

**Comment by MikeNeilson** [comment]
Still not sure why it's working for other things, but I would think this line needs "insert" as well.
https://github.com/opendcs/opendcs/blob/c79d1dea7a8fb27575083e2a849ad083faef73e1/java/opendcs/src/main/resources/db/CWMS-Oracle/callbacks/afterMigrate__vpd_policy.sql#L52

**Comment by ktarbet** [comment]
Today I deleted all NWK OpenDCS data, then imported using dbimport.


The first error is equipment model preventing duplicates. (I'm not concerned about this yet).
Example:
```
FAILURE Could not import equipment model Sutron 8200
FAILURE decodes.db.DatabaseException: Unable to insert properties.
        at decodes.sql.EquipmentModelListIO.insertProperties(EquipmentModelListIO.java:314)
```


However, 3478 errors like the one below are important.
		
```log
DBG1    07/14/25 21:00:11 Will try to write platform 'ODSD-goes' with id=null
DBG1    07/14/25 21:00:11 decodes.cwms.CwmsPlatformListIO.setConnection(637561269)
DBG1    07/14/25 21:00:11 decodes.sql.ConfigListIO.setConnection(637561269)
DBG1    07/14/25 21:00:11 decodes.sql.UnitConverterIO.setConnection(637561269)
DBG1    07/14/25 21:00:11 decodes.sql.EquipmentModelListIO.setConnection(637561269)
DBG2    07/14/25 21:00:11 Executing update query 'INSERT INTO 
Platform (id, agency, isProduction, siteId, configId, description, lastModifyTime, expiration, platformDesignator) 
VALUES (424001, 'USGS', 'FALSE', 1193001, 418001, 'Elm River near Ordway, SD', 
to_date('14-Jul-2025 21:00:11', 'DD-MON-YYYY HH24:MI:SS'), NULL, 'goes')'
WARNING 07/14/25 21:00:11 Cannot write platform ODSD-goes to database: 
WARNING 07/14/25 21:00:11 java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (CCP.OFFICE_SITE_DESIGNATOR_UNIQUE) 
violated on table CCP.PLATFORM columns (DB_OFFICE_CODE, SITEID, PLATFORMDESIGNATOR, EXPIRATION)
ORA-03301: (ORA-00001 details) 
row with column values (DB_OFFICE_CODE:31, SITEID:1193001, PLATFORMDESIGNATOR:'goes', EXPIRATION:NULL) already exists

https://docs.oracle.com/error-help/db/ora-00001/

```


There may be confusion on looking up siteid somewhere.  The query below uses the same siteid (Which I think is a cwms site), but it looks like two different sites.  

```sql
select * from platform where   siteid=1193001;										
```
		
| ID     | AGENCY | ISPRODUCTION | SITEID  | CONFIGID | DESCRIPTION                   | LASTMODIFYTIME | EXPIRATION | PLATFORMDESIGNATOR | DB_OFFICE_CODE |
|--------|--------|--------------|---------|----------|-------------------------------|----------------|------------|--------------------|----------------|
| 416001 | USGS   | FALSE        | 1193001 | 410001   | White River at Oacoma, SD     | 14-Jul-25      |            | goes               | 31             |
| 888001 | USGS   | FALSE        | 1193001 | 755001   | ELM RIVER NEAR ORDWAY,SD      | 14-Jul-25      |            | web                | 31             


In openDCS it looks like this:

<img width="339" height="396" alt="Image" src="https://github.com/user-attachments/assets/f7d14a44-bbbf-4261-b7dc-a6b795ce288e" />



<img width="341" height="413" alt="Image" src="https://github.com/user-attachments/assets/6f012f12-c99a-496b-bf97-b302301ff0c0" />


If this is correct, we may need to modify the constraint on the platform table.
